version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pickles"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-176ko9gbxmwi"
s3_prefix = "pickles"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
