AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  PicklesFunction:
    Type: AWS::Serverless::Function     
    Properties:
      CodeUri: pickles/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        Pickles:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  PicklesApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PicklesFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PicklesFunction.Arn
